sudo apt-get purge  libboost-all-dev 
sudo apt-get purge libboost-coroutine-dev 
sudo apt-get purge  libboost-dbg 
sudo apt-get purge   libboost-doc 
sudo apt-get purge  libboost-exception-dev 
sudo apt-get purge  libboost-graph-dev 
sudo apt-get purge   libboost-graph-parallel-dev 
sudo apt-get purge  libboost-locale-dev 
sudo apt-get purge  libboost-log-dev 
sudo apt-get purge   libboost-math-dev 
sudo apt-get purge  libboost-mpi-dev 
sudo apt-get purge  libboost-mpi-python-dev 
sudo apt-get purge   libboost-program-options-dev 
sudo apt-get purge  libboost-python-dev 
sudo apt-get purge   libboost-random-dev 
sudo apt-get purge  libboost-signals-dev 
sudo apt-get purge  libboost-timer-dev 
sudo apt-get purge   libboost-tools-dev 
sudo apt-get purge  libboost-wave-dev 
